import os
import re
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

REDACTED_API_KEY = "***"
DOTTED_PATH = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$")
IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

ACCURACY = "accuracy"
PERFORMANCE = "performance"

MODEL_IMPORTS = {
    ACCURACY: "ais_bench.benchmark.configs.models.vllm_api.vllm_api_general_chat",
    PERFORMANCE: "ais_bench.benchmark.configs.models.vllm_api.vllm_api_stream_chat",
}
SUMMARIZER_IMPORTS = {
    ACCURACY: "ais_bench.benchmark.configs.summarizers.example",
    PERFORMANCE: "ais_bench.benchmark.configs.summarizers.perf.default_perf",
}
CLI_MODES = {ACCURACY: "all", PERFORMANCE: "perf"}
PERFORMANCE_VISUALIZATION_MODE = "perf_viz"

DEFAULT_MAX_NUM_WORKERS = 1


@dataclass(frozen=True)
class EndpointSnapshot:
    abbr: str
    base_url: str
    model_name: str
    api_key: str | None
    max_output_length: int


def cli_mode_for(mode: str, parameters: dict) -> str:
    if mode == PERFORMANCE and parameters.get("visualization"):
        return PERFORMANCE_VISUALIZATION_MODE
    try:
        return CLI_MODES[mode]
    except KeyError as exc:
        raise ValueError(f"unknown job mode: {mode!r}") from exc


def aisbench_service_url(base_url: str) -> str:
    """Return the service root AISBench appends its own ``v1/...`` endpoint to.

    AISBench builds requests as ``urljoin(base_url, "v1/chat/completions")``, so the value it
    needs is the server root, not the OpenAI-style ``/v1`` prefix users paste in. A trailing
    slash is required or urljoin drops the last path segment.
    """
    parsed = urlsplit(base_url.strip())
    path = parsed.path.rstrip("/")
    path = path.removesuffix("/v1")
    return urlunsplit((parsed.scheme, parsed.netloc, path + "/", "", ""))


def _checked_import(value: str, *, pattern: re.Pattern, label: str) -> str:
    """Import paths come from the packaged catalog; refuse anything that is not a plain name."""
    if not pattern.match(value):
        raise ValueError(f"unsafe config import: {label} {value!r}")
    return value


def render_config(
    *,
    mode: str,
    dataset_import: str,
    dataset_symbol: str,
    endpoint: EndpointSnapshot,
    parameters: dict,
    redact_api_key: bool = False,
) -> str:
    if mode not in MODEL_IMPORTS:
        raise ValueError(f"unknown job mode: {mode!r}")
    dataset_import = _checked_import(dataset_import, pattern=DOTTED_PATH, label="module")
    dataset_symbol = _checked_import(dataset_symbol, pattern=IDENTIFIER, label="symbol")

    service_url = aisbench_service_url(endpoint.base_url)
    parsed = urlsplit(service_url)
    api_key = REDACTED_API_KEY if redact_api_key else (endpoint.api_key or "")

    lines = [
        "# Generated by AISBench Web. Do not edit: submitting the job again replaces this file.",
        "from mmengine.config import read_base",
        "",
        "from ais_bench.benchmark.partitioners import NaivePartitioner",
        "from ais_bench.benchmark.runners.local_api import LocalAPIRunner",
        "from ais_bench.benchmark.tasks import OpenICLInferTask",
        "",
        "with read_base():",
        f"    from {dataset_import} import {dataset_symbol} as datasets",
        f"    from {MODEL_IMPORTS[mode]} import models",
        f"    from {SUMMARIZER_IMPORTS[mode]} import summarizer",
        "",
        "models[0].update(",
        f"    abbr={endpoint.abbr!r},",
        f"    model={endpoint.model_name!r},",
        f"    api_key={api_key!r},",
        f"    host_ip={parsed.hostname or ''!r},",
        f"    host_port={parsed.port or (443 if parsed.scheme == 'https' else 80)!r},",
        f"    url={service_url!r},",
        f"    enable_ssl={(parsed.scheme == 'https')!r},",
        f"    max_out_len={endpoint.max_output_length!r},",
        f"    stream={bool(parameters.get('stream', mode == PERFORMANCE))!r},",
        f"    request_rate={parameters.get('request_rate', 0)!r},",
        ")",
        "",
    ]

    num_prompts = parameters.get("num_prompts")
    if num_prompts is not None:
        lines.append(f"datasets[0]['reader_cfg']['test_range'] = {f'[0:{int(num_prompts)}]'!r}")
        lines.append("")

    workers = int(parameters.get("max_num_workers", DEFAULT_MAX_NUM_WORKERS))
    lines += [
        "infer = dict(",
        "    partitioner=dict(type=NaivePartitioner),",
        "    runner=dict(",
        "        type=LocalAPIRunner,",
        f"        max_num_workers={workers!r},",
        "        task=dict(type=OpenICLInferTask),",
        "    ),",
        ")",
        "",
    ]
    return "\n".join(lines)


def generate_config(
    output: Path,
    *,
    mode: str,
    dataset_import: str,
    dataset_symbol: str,
    endpoint: EndpointSnapshot,
    parameters: dict,
) -> str:
    """Write the job config with owner-only permissions and return its source.

    The returned source contains the decrypted API key, so it must never be logged; use
    ``render_config(..., redact_api_key=True)`` for anything a user or log can see.
    """
    source = render_config(
        mode=mode,
        dataset_import=dataset_import,
        dataset_symbol=dataset_symbol,
        endpoint=endpoint,
        parameters=parameters,
        redact_api_key=False,
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor = os.open(output, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as config_file:
        config_file.write(source)
    output.chmod(0o600)
    return source
